version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: multi-db
    environment:
      POSTGRES_DB: multi_db
      POSTGRES_USER: commonuser
      POSTGRES_PASSWORD: commonpwd
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    container_name: node-app-container
    ports:
      - "3000:3000"
    volumes:
      - ./:/src