INSERT INTO bills (bill_name, bill_url, sponsor_id, cosponsors, yeas, novotes, nays, latest_status, bill_type)
VALUES
    ('S.1838 - Hong Kong Human Rights and Democracy Act of 2019', 'https://www.congress.gov/bill/116th-congress/senate-bill/1838', NULL, ARRAY[19, 20], ARRAY[1, 3, 6, 8, 9, 12, 13, 14, 15], NULL, NULL, 'Became Law', 'Law'),
    ('H.R.7440 - Hong Kong Autonomy Act', 'https://www.congress.gov/bill/116th-congress/house-bill/7440', NULL, NULL, NULL, NULL, NULL, 'Became Law', 'Law'),
    ('S.490 - Hong Kong Economic and Trade Office (HKETO) Certification Act', 'https://www.congress.gov/bill/118th-congress/senate-bill/490', NULL, NULL, NULL, NULL, NULL, 'Introduced', 'Bill'),
    ('S.2710 - A bill to prohibit the commercial export of covered munitions items to the Hong Kong Police Force.', 'https://www.congress.gov/bill/116th-congress/senate-bill/2710', NULL, ARRAY[20], NULL, NULL, NULL, 'Became Law', 'Law'),
    ('S.4110 - Hong Kong Safe Harbor Act', 'https://www.congress.gov/bill/116th-congress/senate-bill/4110', NULL, ARRAY[19], NULL, NULL, NULL, 'Introduced', 'Bill'),
    ('S.295 - Hong Kong Safe Harbor Act', 'https://www.congress.gov/bill/117th-congress/senate-bill/295', NULL, ARRAY[19], NULL, NULL, NULL, 'Introduced', 'Bill'),
    ('S.Res.596 - A resolution expressing the sense of the Senate that the Hong Kong national security law proposed by the Government of the People''s Republic of China would violate the obligations of that government...', 'https://www.congress.gov/bill/116th-congress/senate-resolution/596', NULL, ARRAY[20], NULL, NULL, NULL, 'Agreed to in Senate', 'Resolution'),
    ('H.Res.963 - Expressing the sense of the House of Representatives that the International Olympic Committee should rebid the 2022 Winter Olympic Games to be hosted by a country that recognizes and respects human rights.', 'https://www.congress.gov/bill/116th-congress/house-resolution/963', NULL, ARRAY[6], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('S.Res.608 - A resolution expressing the sense of the Senate condemning threats to Hong Kong''s freedoms and autonomy on the 31st anniversary of the violent repression of the peaceful protests centered in Beijing''s Tiananmen Square.', 'https://www.congress.gov/bill/116th-congress/senate-resolution/608', NULL, ARRAY[19], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('H.Res.974 - Expressing the sense of the House of Representatives that the Hong Kong national security law proposed by the Government of the People''s Republic of China would violate the obligations of that Government...', 'https://www.congress.gov/bill/116th-congress/house-resolution/974', NULL, ARRAY[6], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('S.Res.526 - A resolution expressing the sense of the Senate that the International Olympic Committee should rebid the 2022 Winter Olympic games to be hosted by a country that recognizes and respects human rights.', 'https://www.congress.gov/bill/116th-congress/senate-resolution/56', NULL, ARRAY[19], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('S.Res.106 - A resolution condemning Beijing''s destruction of Hong Kong''s democracy and rule of law.', 'https://www.congress.gov/bill/118th-congress/senate-resolution/106', NULL, ARRAY[19, 20], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('H.Res.462 - Remembering the victims of the 1989 Tiananmen Square massacre and condemning the continued and intensifying crackdown on human rights and basic freedoms within the People''s Republic of China...', 'https://www.congress.gov/bill/118th-congress/house-resolution/462', NULL, ARRAY[13], NULL, NULL, NULL, 'Introduced', 'Resolution'),
    ('S.Res.126 - A resolution condemning the crackdown by the Government of the People''s Republic of China and the Chinese Communist Party in Hong Kong, including the arrests of pro-democracy activists and repeated violations of the obligations of that Government...', 'https://www.congress.gov/bill/117th-congress/senate-resolution/126', NULL, ARRAY[19, 20], NULL, NULL, NULL, 'Introduced', 'Resolution');
